[2021-09-05T17:56:46.8722782] org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://127.0.0.1/u382793551_Xeros?useSSL=false&serverTimezone=UTC) for user 'root': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

[2021-09-05T17:56:46.8762817] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:71)
[2021-09-05T17:56:46.8762817] 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:68)
[2021-09-05T17:56:46.8762817] 	at org.flywaydb.core.Flyway.execute(Flyway.java:506)
[2021-09-05T17:56:46.8772824] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:172)
[2021-09-05T17:56:46.8772824] 	at io.xeros.Server.loadData(Server.java:136)
[2021-09-05T17:56:46.8772824] 	at io.xeros.Server.lambda$main$0(Server.java:172)
[2021-09-05T17:56:46.8772824] 	at io.xeros.GameThread.run(GameThread.java:52)
[2021-09-05T17:56:46.8772824] Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-09-05T17:56:46.8772824] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[2021-09-05T17:56:46.8772824] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[2021-09-05T17:56:46.8772824] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[2021-09-05T17:56:46.8772824] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[2021-09-05T17:56:46.8772824] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[2021-09-05T17:56:46.8772824] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[2021-09-05T17:56:46.8772824] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:268)
[2021-09-05T17:56:46.8772824] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:232)
[2021-09-05T17:56:46.8782837] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:55)
[2021-09-05T17:56:46.8782837] 	... 6 more
[2021-09-05T17:56:46.8782837] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-09-05T17:56:46.8782837] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-09-05T17:56:46.8782837] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
[2021-09-05T17:56:46.8782837] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-09-05T17:56:46.8782837] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2021-09-05T17:56:46.8782837] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2021-09-05T17:56:46.8782837] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[2021-09-05T17:56:46.8782837] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[2021-09-05T17:56:46.8782837] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[2021-09-05T17:56:46.8792845] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[2021-09-05T17:56:46.8792845] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[2021-09-05T17:56:46.8792845] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[2021-09-05T17:56:46.8792845] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[2021-09-05T17:56:46.8792845] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[2021-09-05T17:56:46.8792845] 	... 12 more
[2021-09-05T17:56:46.8792845] Caused by: java.net.ConnectException: Connection refused: connect
[2021-09-05T17:56:46.8792845] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-09-05T17:56:46.8792845] 	at java.base/sun.nio.ch.Net.connect(Net.java:574)
[2021-09-05T17:56:46.8792845] 	at java.base/sun.nio.ch.Net.connect(Net.java:563)
[2021-09-05T17:56:46.8792845] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-09-05T17:56:46.8792845] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[2021-09-05T17:56:46.8802848] 	at java.base/java.net.Socket.connect(Socket.java:648)
[2021-09-05T17:56:46.8802848] 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[2021-09-05T17:56:46.8802848] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[2021-09-05T17:56:46.8802848] 	... 15 more
[2021-09-05T17:56:58.9682967] org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://127.0.0.1/u382793551_Xeros?useSSL=false&serverTimezone=UTC) for user 'root': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

[2021-09-05T17:56:58.9702985] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:71)
[2021-09-05T17:56:58.9712994] 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:68)
[2021-09-05T17:56:58.9712994] 	at org.flywaydb.core.Flyway.execute(Flyway.java:506)
[2021-09-05T17:56:58.9712994] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:172)
[2021-09-05T17:56:58.9712994] 	at io.xeros.Server.loadData(Server.java:136)
[2021-09-05T17:56:58.9712994] 	at io.xeros.Server.lambda$main$0(Server.java:172)
[2021-09-05T17:56:58.9712994] 	at io.xeros.GameThread.run(GameThread.java:52)
[2021-09-05T17:56:58.9712994] Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-09-05T17:56:58.9712994] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[2021-09-05T17:56:58.9712994] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[2021-09-05T17:56:58.9712994] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[2021-09-05T17:56:58.9712994] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[2021-09-05T17:56:58.9712994] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[2021-09-05T17:56:58.9712994] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[2021-09-05T17:56:58.9723005] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:268)
[2021-09-05T17:56:58.9723005] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:232)
[2021-09-05T17:56:58.9723005] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:55)
[2021-09-05T17:56:58.9723005] 	... 6 more
[2021-09-05T17:56:58.9723005] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-09-05T17:56:58.9723005] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-09-05T17:56:58.9723005] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
[2021-09-05T17:56:58.9723005] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-09-05T17:56:58.9723005] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2021-09-05T17:56:58.9723005] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2021-09-05T17:56:58.9723005] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[2021-09-05T17:56:58.9723005] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[2021-09-05T17:56:58.9723005] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[2021-09-05T17:56:58.9733012] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[2021-09-05T17:56:58.9733012] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[2021-09-05T17:56:58.9733012] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[2021-09-05T17:56:58.9733012] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[2021-09-05T17:56:58.9733012] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[2021-09-05T17:56:58.9733012] 	... 12 more
[2021-09-05T17:56:58.9733012] Caused by: java.net.ConnectException: Connection refused: connect
[2021-09-05T17:56:58.9733012] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-09-05T17:56:58.9733012] 	at java.base/sun.nio.ch.Net.connect(Net.java:574)
[2021-09-05T17:56:58.9733012] 	at java.base/sun.nio.ch.Net.connect(Net.java:563)
[2021-09-05T17:56:58.9733012] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-09-05T17:56:58.9743021] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[2021-09-05T17:56:58.9743021] 	at java.base/java.net.Socket.connect(Socket.java:648)
[2021-09-05T17:56:58.9743021] 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[2021-09-05T17:56:58.9743021] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[2021-09-05T17:56:58.9743021] 	... 15 more
[2021-09-05T17:57:28.2394512] org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://127.0.0.1/u382793551_Xeros?useSSL=false&serverTimezone=UTC) for user 'root': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

[2021-09-05T17:57:28.2424532] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:71)
[2021-09-05T17:57:28.2424532] 	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:68)
[2021-09-05T17:57:28.2424532] 	at org.flywaydb.core.Flyway.execute(Flyway.java:506)
[2021-09-05T17:57:28.2424532] 	at org.flywaydb.core.Flyway.migrate(Flyway.java:172)
[2021-09-05T17:57:28.2424532] 	at io.xeros.Server.loadData(Server.java:136)
[2021-09-05T17:57:28.2424532] 	at io.xeros.Server.lambda$main$0(Server.java:172)
[2021-09-05T17:57:28.2424532] 	at io.xeros.GameThread.run(GameThread.java:52)
[2021-09-05T17:57:28.2424532] Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-09-05T17:57:28.2424532] 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
[2021-09-05T17:57:28.2424532] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[2021-09-05T17:57:28.2424532] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
[2021-09-05T17:57:28.2434542] 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
[2021-09-05T17:57:28.2434542] 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
[2021-09-05T17:57:28.2434542] 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[2021-09-05T17:57:28.2434542] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:268)
[2021-09-05T17:57:28.2434542] 	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:232)
[2021-09-05T17:57:28.2434542] 	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:55)
[2021-09-05T17:57:28.2434542] 	... 6 more
[2021-09-05T17:57:28.2434542] Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[2021-09-05T17:57:28.2434542] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-09-05T17:57:28.2434542] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
[2021-09-05T17:57:28.2434542] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-09-05T17:57:28.2434542] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2021-09-05T17:57:28.2434542] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
[2021-09-05T17:57:28.244455] 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
[2021-09-05T17:57:28.244455] 	... 12 more
[2021-09-05T17:57:28.244455] Caused by: java.net.ConnectException: Connection refused: connect
[2021-09-05T17:57:28.244455] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[2021-09-05T17:57:28.244455] 	at java.base/sun.nio.ch.Net.connect(Net.java:574)
[2021-09-05T17:57:28.2454564] 	at java.base/sun.nio.ch.Net.connect(Net.java:563)
[2021-09-05T17:57:28.2454564] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[2021-09-05T17:57:28.2454564] 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[2021-09-05T17:57:28.2454564] 	at java.base/java.net.Socket.connect(Socket.java:648)
[2021-09-05T17:57:28.2454564] 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
[2021-09-05T17:57:28.2454564] 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
[2021-09-05T17:57:28.2454564] 	... 15 more
Sep 05, 2021 5:57:54 PM io.xeros.content.boosts.Boosts init
INFO: Loaded 16 boosts.
Sep 05, 2021 5:57:55 PM io.xeros.model.definitions.ItemDef load
INFO: Loaded 14046 item definitions.
Sep 05, 2021 5:57:55 PM io.xeros.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Sep 05, 2021 5:57:55 PM io.xeros.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Sep 05, 2021 5:57:55 PM io.xeros.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 2926 npcs.
Sep 05, 2021 5:57:55 PM io.xeros.model.entity.npc.NPCRelationship setup
INFO: Initialized 36 npc relationships.
Sep 05, 2021 5:57:55 PM io.xeros.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Sep 05, 2021 5:58:02 PM io.xeros.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Sep 05, 2021 5:58:02 PM io.xeros.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Sep 05, 2021 5:58:02 PM io.xeros.content.commands.CommandManager initializeCommands
INFO: Loaded 238 commands.
Sep 05, 2021 5:58:02 PM io.xeros.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Sep 05, 2021 5:58:02 PM io.xeros.content.dailyrewards.DailyRewardsRecords load
WARNING: No daily reward claims found.
Sep 05, 2021 5:59:13 PM io.xeros.content.boosts.Boosts init
INFO: Loaded 16 boosts.
Sep 05, 2021 5:59:14 PM io.xeros.model.definitions.ItemDef load
INFO: Loaded 14046 item definitions.
Sep 05, 2021 5:59:14 PM io.xeros.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Sep 05, 2021 5:59:14 PM io.xeros.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Sep 05, 2021 5:59:14 PM io.xeros.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 2926 npcs.
Sep 05, 2021 5:59:14 PM io.xeros.model.entity.npc.NPCRelationship setup
INFO: Initialized 36 npc relationships.
Sep 05, 2021 5:59:14 PM io.xeros.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Sep 05, 2021 5:59:20 PM io.xeros.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Sep 05, 2021 5:59:20 PM io.xeros.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Sep 05, 2021 5:59:20 PM io.xeros.content.commands.CommandManager initializeCommands
INFO: Loaded 238 commands.
Sep 05, 2021 5:59:20 PM io.xeros.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Sep 05, 2021 5:59:20 PM io.xeros.content.dailyrewards.DailyRewardsRecords load
WARNING: No daily reward claims found.
Sep 05, 2021 6:00:17 PM io.xeros.content.boosts.Boosts init
INFO: Loaded 16 boosts.
Sep 05, 2021 6:00:17 PM io.xeros.model.definitions.ItemDef load
INFO: Loaded 14046 item definitions.
Sep 05, 2021 6:00:17 PM io.xeros.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Sep 05, 2021 6:00:17 PM io.xeros.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Sep 05, 2021 6:00:17 PM io.xeros.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 2926 npcs.
Sep 05, 2021 6:00:17 PM io.xeros.model.entity.npc.NPCRelationship setup
INFO: Initialized 36 npc relationships.
Sep 05, 2021 6:00:17 PM io.xeros.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Sep 05, 2021 6:00:23 PM io.xeros.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Sep 05, 2021 6:00:23 PM io.xeros.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Sep 05, 2021 6:00:23 PM io.xeros.content.commands.CommandManager initializeCommands
INFO: Loaded 238 commands.
Sep 05, 2021 6:00:23 PM io.xeros.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Sep 05, 2021 6:00:23 PM io.xeros.content.dailyrewards.DailyRewardsRecords load
WARNING: No daily reward claims found.
Sep 05, 2021 6:01:35 PM io.xeros.content.boosts.Boosts init
INFO: Loaded 16 boosts.
Sep 05, 2021 6:01:35 PM io.xeros.model.definitions.ItemDef load
INFO: Loaded 14046 item definitions.
Sep 05, 2021 6:01:35 PM io.xeros.model.definitions.NpcStats load
INFO: Loaded 2906 npc stats.
Sep 05, 2021 6:01:35 PM io.xeros.model.definitions.ItemStats load
INFO: Loaded 9767 item stats.
Sep 05, 2021 6:01:35 PM io.xeros.model.entity.npc.NpcSpawnLoader load
INFO: Spawned 2926 npcs.
Sep 05, 2021 6:01:35 PM io.xeros.model.entity.npc.NPCRelationship setup
INFO: Initialized 36 npc relationships.
Sep 05, 2021 6:01:35 PM io.xeros.model.lobby.LobbyManager initializeLobbies
INFO: Initialized 2 lobbies.
Sep 05, 2021 6:01:41 PM io.xeros.model.collisionmap.Region load
INFO: Loaded 52 custom maps.
Sep 05, 2021 6:01:41 PM io.xeros.model.collisionmap.Region load
INFO: Error loading map files: [1182, 1183, 3642, 3643, 3648, 3649]
Sep 05, 2021 6:01:41 PM io.xeros.content.commands.CommandManager initializeCommands
INFO: Loaded 238 commands.
Sep 05, 2021 6:01:42 PM io.xeros.content.dailyrewards.DailyRewardContainer load
INFO: Selected daily rewards path with start date: 2021-07-01
Sep 05, 2021 6:01:42 PM io.xeros.content.dailyrewards.DailyRewardsRecords load
WARNING: No daily reward claims found.
